# Generated by Django 2.2.1 on 2019-05-03 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_class',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
